.github/scripts/check_diff.py
libs/ai-endpoints/poetry.lock
libs/ai-endpoints/pyproject.toml

this is necessary now that the code is outside the langchain repository

fix location of landchain-core dependency

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/embeddings.py
libs/ai-endpoints/poetry.lock
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/unit_tests/test_embeddings.py

resolves https://github.com/langchain-ai/langchain-nvidia/issues/8

validate NVIDIAEmbeddings.embed_documents input type is list[str]

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/tests/integration_tests/test_api_key.py
libs/ai-endpoints/tests/unit_tests/test_api_key.py

When a user tries to initialize a model without having an API key pulled in from the environment of constructor, it fails because the API key will be none. The one-line fix on top addresses this. 
An invalid key will cause an error from the server, and current code in try_raise will miss it due to a change in error message structure. A minimal modification is implemented to quickly remedy this. Further testing necessary later to see what all we might encounter in the error message space.

Fix missing api_key = None issue and try_raise parsing miss

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/embeddings.py
libs/ai-endpoints/poetry.lock
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_chat_models.py
libs/ai-endpoints/tests/integration_tests/test_embeddings.py

- add support for ai-embed-qa-4 mode on API Catalog
- no api change

add api catalog embeddings

---

libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_embeddings.py

the existing code supports both NVIDIAEmbeddings communication with the NVIDIA API Catalog as well as a downloaded NVIDIA NIM.
this PR only provides test plumbing to validate the NIM support.
currently, there is no NIM CI infrastructure, so the tests must be run manually.
after setting up an embedding NIM on port 8082, use `poetry run pytest tests/integration_tests/test_embeddings.py --nim-endpoint http://localhost:8082/v1 --embedding-model-id NV-Embed-QA -vv`

add tests for NVIDIAEmbeddings().mode("nim", base_url="http://.../v1") support

---

libs/ai-endpoints/docs/text_embedding/nvidia_ai_endpoints.ipynb
libs/ai-endpoints/langchain_nvidia_ai_endpoints/embeddings.py
libs/ai-endpoints/tests/integration_tests/test_embeddings.py
libs/ai-endpoints/tests/unit_tests/test_embeddings.py

options are -
- "NONE" (default), do not truncate and raise an exception if the input is too long
- "END", truncate tokens from the right side of the input
- "START", truncate tokens from the left side of the input
future: consider END/RIGHT/BOTTOM and START/LEFT/TOP aliases for better language support
note: NONE is the default because it is the service's default, most users will pick END
fixes #20

add truncate parameter for shortening inputs to match model token length limits

---

libs/ai-endpoints/docs/retrievers/nvidia_rerank.ipynb
libs/ai-endpoints/langchain_nvidia_ai_endpoints/reranking.py
libs/ai-endpoints/tests/integration_tests/test_ranking.py

this is an extension of the NVIDIARerank api to work with a local NIM, all expectations about NVIDIARerank persist plus the following -
```
ranker = NVIDIARerank().mode("nim", base_url="http://localhost:1976/v1")
```
this builds off #19

add NVIDIARerank support for a local NIM

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/reranking.py
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_chat_models.py
libs/ai-endpoints/tests/integration_tests/test_embeddings.py
libs/ai-endpoints/tests/integration_tests/test_other_models.py
libs/ai-endpoints/tests/integration_tests/test_ranking.py
libs/ai-endpoints/tests/unit_tests/test_chat_models.py

To simplify and align switching from hosted and local backends, the `mode()` method is deprecated in favor of using `base_url` passed to constructors.
The `mode()` method will be removed in v0.1.
Old usage -
```
from langchain_nvidia_ai_endpoints import ChatNVIDIA, NVIDIAEmbeddings, NVIDIARerank
llm = ChatNVIDIA().mode("nim", base_url="http://localhost:8000/v1")
embedder = NVIDIAEmbeddings().mode("nim", base_url="http://localhost:12345/v1")
ranker = NVIDIARerank().mode("nim", base_url="http://localhost:1976/v1")
```
New usage -
```
from langchain_nvidia_ai_endpoints import ChatNVIDIA, NVIDIAEmbeddings, NVIDIARerank
llm = ChatNVIDIA(base_url="http://localhost:8000/v1")
embedder = NVIDIAEmbeddings(base_url="http://localhost:12345/v1")
ranker = …
```

Deprecate mode() in favor of __init__(base_url=...)

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/embeddings.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/reranking.py

previously, if a model was known to be hosted on a custom endpoint and a user ran the same model locally, the connectors would favor the hosted version. for instance, NVIDIAEmbeddings(model="NV-Embed-QA", base_url="http://localhost/v1") would contact the hosted NV-Embed-QA. likewise, ChatNVIDIA(model="mistralai/mixtral-8x7b-instruct-v0.1", base_url="http://localhost/v1") would contact the hosted mistralai/mixtral-8x7b-instruct-v0.1.
fixes #31

make connectors use user provided base_url when the provided model is also hosted

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/tests/integration_tests/test_api_key.py
libs/ai-endpoints/tests/unit_tests/test_api_key.py

Fix for the client as the output includes the Bearer key, unredacted.

Fix for NVIDIAClient output to redact the api_key

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/tests/integration_tests/test_chat_models.py
libs/ai-endpoints/tests/unit_tests/test_stop.py

`ChatNVIDIA(..., stop=...)` would not change the `stop` words for `invoke`
fixed `_generate` logic and added tests for `stop` across `invoke` and `stream`
future - we should deprecate the `stop` property on `ChatNVIDIA`

make stop property functional

---

libs/ai-endpoints/docs/chat/nvidia_ai_endpoints.ipynb
libs/ai-endpoints/docs/text_embedding/nvidia_ai_endpoints.ipynb
libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/embeddings.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/reranking.py
libs/ai-endpoints/tests/unit_tests/test_api_key.py
libs/ai-endpoints/tests/unit_tests/test_base_url.py
libs/ai-endpoints/tests/unit_tests/test_model.py

New implementation:
This can be simplified by using the first available model if none is provided, e.g.
llm = ChatNVIDIA(base_url="http://localhost:1234/v1")
llm.chat(...)
llm._client.model => default model => first available model in local NIM
Fixes:
- Display of the lora variants in local NIM mode
- _lint.yml workflow update for the failing lint checks

Provide default model in local NIM mode

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py

preparing the main branch for function calling with small changes.
- inline _prep_payload, _get_filled_chunk, _preprocess_msg
- remove _get_astream

refactor payload preprocessing

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/__init__.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py
libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_api_key.py
libs/ai-endpoints/tests/integration_tests/test_base_url.py
libs/ai-endpoints/tests/integration_tests/test_register_model.py
libs/ai-endpoints/tests/unit_tests/conftest.py
libs/ai-endpoints/tests/unit_tests/test_imports.py
libs/ai-endpoints/tests/unit_tests/test_register_model.py

this expands the public api with a `Model` class and `register_model` function.
background: we currently support hosted (base_url of integration.api.nvidia.com/v1) as well as local NIMs (base_url controlled by user, e.g. localhost:1234/v1) using the `base_url` feature. the base_url must provide paths for model listing,  `/models`, and inference, one of  `/chat/completion`, `/embeddings` or `/ranking`.
use case:  users would like to support endpoints that only support inference (do not support model listing) and to minimize code changes when model names stay the same and endpoints change.
design -
```
from langchain_nvidia_ai_endpoints import register_model, Model, ChatNVIDIA
register_model(Model(id="my-custom-model-name", model_type="chat", client="ChatNVIDIA", …
```

add register_model for users to add their own custom models with endpoints [api change; expansion]

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/tests/integration_tests/test_chat_models.py

remove the client side stop word detection and rely on server side implementation
two issues with client side implementation -
1. it was not being called in the v0.1 series (last worked in v0.0.20), effectively didn't work
2. it would return part of the stop word (`find(...) + 1`)
this simplifies the output post-processing, which moves us toward using standard post-processing tools.

remove broken stop word detection, rely on server side implementation

---

libs/ai-endpoints/docs/retrievers/nvidia_rerank.ipynb
libs/ai-endpoints/langchain_nvidia_ai_endpoints/reranking.py
libs/ai-endpoints/tests/integration_tests/test_ranking.py
libs/ai-endpoints/tests/unit_tests/test_ranking.py

rerank models now reject large input by default and provide a truncate parameter to control this behavior.
add optional `truncate` per -
```
truncate: Optional[Literal["NONE", "END"]] = Field(
description=
"Truncate input text if it exceeds the model's maximum token length. "
"Default is model dependent and is likely to raise error if an "
"input is too long."
```
usage -
```
from langchain_nvidia_ai_endpoints import NVIDIARerank
query = "What is acceleration?"
ranker = NVIDIARerank(model=rerank_model, truncate="END")
result = client.compress_documents(documents=large_documents, query=query)
```

add support for reranking api change w/ truncate parameter

---

libs/ai-endpoints/docs/chat/nvidia_ai_endpoints.ipynb
libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/poetry.lock
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_bind_tools.py
libs/ai-endpoints/tests/integration_tests/test_chat_models.py
libs/ai-endpoints/tests/integration_tests/test_vlm_models.py
libs/ai-endpoints/tests/unit_tests/test_parallel_tool_calls.py

```
from langchain_core.pydantic_v1 import Field
from langchain_core.tools import tool
from langchain_nvidia_ai_endpoints import ChatNVIDIA
@tool
def xxyyzz(
a: int = Field(..., description="First number"),
b: int = Field(..., description="Second number"),
) -> int:
"""xxyyzz two numbers"""
return (a**b) % (b - a)
llm = ChatNVIDIA(model=tool_model, **mode).bind_tools(tools=[xxyyzz])
```
invoke -
```
response = llm.invoke("What is 11 xxyyzz 3?", tool_choice="required")
print(response.tool_calls)
```
streaming -
```
from functools import reduce
from operator import add
response = reduce(add, llm.stream("What is 11 xxyyzz 3?", tool_choice="required")
print(response.tool_calls)
```
**Note:** `stream` now returns an `AIMessageChunk`. The old behavior was to return a `ChatMessageChunk`. This …

add chat tool calling

---

libs/ai-endpoints/docs/chat/nvidia_ai_endpoints.ipynb
libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_structured_output.py
libs/ai-endpoints/tests/unit_tests/conftest.py
libs/ai-endpoints/tests/unit_tests/test_structured_output.py

Bind a structured output schema to the model.
The schema can be -
0. a dictionary representing a JSON schema
1. a Pydantic object
2. an Enum
0. If a dictionary is provided, the model will return a dictionary. Example:
```
json_schema = {
"title": "joke",
"description": "Joke to tell user.",
"type": "object",
"properties": {
"setup": {
"type": "string",
"description": "The setup of the joke",
},
"punchline": {
"type": "string",
"description": "The punchline to the joke",
},
},
"required": ["setup", "punchline"],
}
structured_llm = llm.with_structured_output(json_schema)
structured_llm.invoke("Tell me a joke about NVIDIA")
```
1. If a Pydantic schema is provided, the model will return a Pydantic object.
Example:
```
from langchain_core.pydantic_v1 import BaseModel, Field
class …
```

add with_structured_output support for Pydantic models, dicts and Enum

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/scripts/check_pydantic.sh
libs/ai-endpoints/tests/unit_tests/test_structured_output.py

`with_structured_output` should accept types built from `langchain_core.pydantic_v1` + `pydantic.v1` + `pydantic`
previously only `langchain_core.pydantic_v1` types were supported.

support pydantic v2 and v1 for with_structured_output

---

libs/ai-endpoints/poetry.lock
libs/ai-endpoints/pyproject.toml

Update min version for langchain-core

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/tests/integration_tests/test_streaming.py

stream responses are being collected and distributed to users after inference has completed.
this fixes the behavior to distribute streamed chunks as they become available.

bug: fix stream collection

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py

Correcting the url validation logic by adding "v1" to endpoints for failing test cases.

fix failing test cases for base url

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py
libs/ai-endpoints/tests/integration_tests/test_bind_tools.py
libs/ai-endpoints/tests/unit_tests/test_bind_tools.py

for `invoke` and `stream`, no token usage information is returned.
this change allows for inclusion of the token usage information.
tests are in the LC standard suite, which will be merged soon.

feat: include usage metadata

---

libs/ai-endpoints/langchain_nvidia.py
libs/ai-endpoints/langchain_nvidia_ai_endpoints/__init__.py
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/unit_tests/test_imports.py

this allows users to `from langchain_nvidia import ChatNVIDIA` as an alternative to `from langchain_nvidia_ai_endpoints import ChatNVIDIA`
what this does not do -
- prevent users from continuing to import from `langchain_nvidia_ai_endpoints`
- allow you to `pip install langchain-nvidia`, you must still `pip install langchain-nvidia-ai-endpoints` (worthwhile RFE)

allow `import langchain_nvidia`

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/pyproject.toml
libs/ai-endpoints/tests/unit_tests/test_base_url.py

allow base_url to work with proxies, e.g. http://host/proxy/path/v1

---

libs/ai-endpoints/tests/integration_tests/test_standard.py

this is intended to align w/ the default test model for other tests and address accuracy issues

update the standard test model from llama 3.1 8b to 3.3 70b

---

libs/ai-endpoints/tests/integration_tests/conftest.py
libs/ai-endpoints/tests/integration_tests/test_vlm_models.py

- updating the default llm model to `meta/llama-3.2-11b-vision-instruct`
- marked `test_vlm_models.py::test_vlm_two_images` test as xfail as it continuously fails for the above model
cc: @dglogo @sumitb

Scheduled CI test vlm case fix

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py

The QA models also do not accept the stream_options entry.

Drop stream_options for qa models too.

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py

- meta/llama-4-maverick-17b-128e-instruct
- meta/llama-4-scout-17b-16e-instruct
Integrations test case:
returning a generic "Bad request" + "Inference error" message for: negative max_tokens, Temperature, top_p
Have raised a bug internally.
cc: @dglogo, @mattf

add support for llama-4 models

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/tests/unit_tests/test_base_url.py

replaces #148 
maintain the current behavior for now, but deprecate the feature in the following release.

Updated warnings for api version check.

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_common.py
libs/ai-endpoints/tests/unit_tests/test_base_url.py

Setting `APPEND_NVIDIA_API_VERSION` to `False`, `false`, or `0` will disable the `/v1` check.
Unit test added to verify this behavior.

Added option to  skip api  url checking.

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/chat_models.py

This change will let users use the `with_thinking_mode `with a warning in case the model is not known to support thinking. This was done keeping `nvdev` models in mind so that users don't need to register models every time with thinking support to use it.

relax nemotron thinking warning for nvdev models

---

libs/ai-endpoints/langchain_nvidia_ai_endpoints/_statics.py

- Add tool call support to [nvidia/llama-3.3-nemotron-super-49b-v1](https://build.nvidia.com/nvidia/llama-3_3-nemotron-super-49b-v1) and [nvidia/llama-3.3-nemotron-super-49b-v1.5](https://build.nvidia.com/nvidia/llama-3_3-nemotron-super-49b-v1_5).

Add tool call support to llama-3.3-nemotron-super-49b v1 and v1.5
